version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ai-service:
    build: ./services/ai-service
    environment:
      DATABASE_URL: postgres://nexus:nexus@postgres:5432/nexus
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  auth-service:
    build: ./services/auth-service
    environment:
      DATABASE_URL: postgres://nexus:nexus@postgres:5432/nexus
    ports:
      - "8002:8002"
    depends_on:
      - postgres

volumes:
  postgres-data:
